version: '3.9'

services:
  eventary-api:
    image: xitsmarleen/eventary-api:latest
    container_name: eventary-api
    ports:
      - "5254:5254"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 eventary-api
